- src/adapters/polkadot.ts
Without this, the transfer fails with a misleading error message. The reason is that kusama doesn't realize our chain supports xcm v2, so it converts all messages to xcm v1 before sending it to us. It just happens that xcm v1 doesn't support the WeightLimit::Unlimited item, causing it to fail. The solution is to switch to an extrinsic that doesn't set an unlimited weight
> fix: dont use limited_reserve_transfer for kusama->kintsugi

- package.json
Change Polkadot peer dependency to 9 or newer
Bump version of @interlay/bridge to 0.1.0
> Chore: update peer dependency version

- .github/workflows/npm.yml
Add `always-auth` and `registry-url` params for npm publish action to work.
> Fix: add always-auth and registry-url params to npm github actions

- package.json
- src/adapters/interlay.ts
- src/adapters/moonbeam.ts
- src/bridge.spec.ts
No reverse xcm yet, as we don't have an adapter for tx originating from moonbeam yet.
> Feat: Add xcm for INTR, IBTC from Interlay to Moonbeam

- src/api-provider.spec.ts
- src/api-provider.ts
Primarily by adding `noInitWarn` flag to get rid of warnings about non-decorated rpc apis for each adapter/connection.
Also reenabled a test that has been commented out previously.
> Chore: reduce logging verbosity

- .github/workflows/pr-any.yml
- package.json
- src/adapters/interlay.ts
- src/adapters/polkadot.ts
- src/api-provider.spec.ts
- src/bridge.spec.ts
Updated xcm fees for sending KSM from kintsugi to kusama and back, as well as for sending DOT from polkadot to interlay and back.
> Chore: Adjust xcm fees

- src/adapters/interlay.spec.ts
- src/adapters/interlay.ts
- src/adapters/parallel.spec.ts
- src/adapters/parallel.ts
- src/bridge.spec.ts
- src/configs/chains/kusama-chains.ts
- src/utils/shared-spec-methods.ts
Resolves #43 
Add XCM support for Heiko: KBTC
Links to constructed test tx:
- [kintsugi -> heiko](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fapi-kusama.interlay.io%2Fparachain#/extrinsics/decode/0x5e00000b00e40b54020000000000000000000000010102009520010034b83f611d47a5acf4c641b0ee86d746ffca91e1bb616a00a0f43e96184313780008d6e829000000)
- [heiko -> kintsugi](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fheiko-rpc.parallel.fi#/extrinsics/decode/0x2b007900000000e40b5402000000000000000000000001010200b120010034b83f611d47a5acf4c641b0ee86d746ffca91e1bb616a00a0f43e961843137800)
> Feat: add Heiko kbtc

- src/adapters/acala.ts
- src/adapters/bifrost.ts
- src/adapters/interlay.ts
- src/adapters/parallel.ts
- src/bridge.spec.ts
- src/utils/xtokens-dest-weight.ts
Resolves #59 
Use "Unlimited" as destination weight for `xTokens.transfer` if supported, otherwise use existing format of a numeric (u64) destination weight as defined in the adapters' configurations.
> Feat: future proof xtokens transfer

- src/adapters/acala.ts
- src/adapters/interlay.ts
- src/adapters/parallel.ts
- src/adapters/polkadot.ts
Output from testing script prior to this change:
```
Testing KBTC transfer from karura to kintsugi... WARN
⚠️ Fees need to be increased in config. The actual fees are 0.00000107 (= 107 plank). Fee overestimation factor was 1.86915887 - we want at least 2.0
Testing KBTC transfer from kintsugi to heiko... WARN
⚠️ Fees need to be increased in config. The actual fees are 0.00000103 (= 103 plank). Fee overestimation factor was 1.94174757 - we want at least 2.0
Testing KBTC transfer from heiko to kintsugi... WARN
⚠️ Fees need to be increased in config. The actual fees are 0.00000107 (= 107 plank). Fee overestimation factor was 1.86915887 - we want at least 2.0
```
I set a 10x margin for each of these.
Also the existential deposit on kusama was too low. The on-chain info:
```
const …
```
> fix: fees and eds

- package.json
- scripts/chopsticks-test.ts
This is step 1 of https://github.com/interlay/bridge/issues/54
> test: test bridge using chopsticks

- scripts/chopsticks-test.ts
Use the new-and-improved™ api provider constructor, now containing less than one argument.
> Fix: ApiProvider constructor change

- package.json
- tsconfig.json
Build output paths changed after adding `scripts` folder - introducing subfolder `src` and `scripts`. Previously the build folder contained `src` contents directly. 
This fixes the paths again by ignoring `scripts` folder for build output.
> Fix: broken build output paths

- .github/workflows/xcm-tests.yml
- scripts/chopsticks-test.ts
Disable xcm tests temporarily for:
- Kusama
- Statemine
To be reenabled with PR #73
> Chore: update tests

- package.json
- scripts/chopsticks-test.ts
- src/adapters/polkadot.ts
- src/adapters/statemint.ts
- src/bridge.spec.ts
- src/utils/polkadotXcm-multilocation-check.ts
- yarn.lock
❗ TODO before merging:
Test extrinsic KSM from Kusama to Kintsugi, receiving account id is Alice: `0x630203000100b1200300010100d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d030400000000821a060000000000`
_Edit_: ^ The amount in the extrinsic above was too low. Had to increase it so it was larger than the xcm fees.
> Hotfix: kusama statemint upgrades

- package.json
- src/adapters/bifrost.ts
Updating Bifrost adapter to utilize V3 xcm multilocations instead of V1 when required.
Tested VKSM transactions:
- ✅ Kintsugi -> Bifrost. Actual fees are similar to before, no change to fee estimates
- ✅ Bifrost -> Kintsugi. Actual fees are identical to before, no change to fee estimates
Extrinsics used for chopsticks tests (from Alice to Alice):
Kintsugi -> Bifrost
```
0x5e00010500000000e40b5402000000000000000000000001010200451f0100d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d00
```
Bifrost -> Kintsugi
```
0x4600010400e40b5402000000000000000000000003010200b1200100d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d00
```
> Fix: bifrost xtokens transfer multilocations

- .github/workflows/xcm-tests.yml
- scripts/chopsticks-test.ts
- scripts/interlay-chopsticks-test.ts
- scripts/kintsugi-chopsticks-test.ts
Identify available to/from routers and tokens to run chopsticks tests against, and apply filter to skip test cases if a filter is provided.
> Refactor: Auto identify test cases for chopsticks

- package.json
- src/utils/xtokens-helper.ts
We need this for our next runtime upgrade
> fix: check for xcm v3 argument in xtokens.transfer

- package.json
- src/adapters/polkadot.ts
Revert previous changes, and use `derive.balances.all` storage instead of `query.system.account` to find an account's balance on Polkadot and Kusama.
> Chore: use derived balance for polkadot, kusama

- src/adapters/interlay.spec.ts
- src/base-chain-adapter.ts
Temporary fix to have some fee estimate even if `tx.paymentInfo` is not available in polkadot.js
> fix: return fallback estimate if paymentInfo is unavailable

- .github/workflows/xcm-tests.yml
- scripts/interlay-chopsticks-test.ts
- src/adapters/interlay.ts
Astar is testable now that the chopsticks config changed to a different rpc node. The re-enabled test revealed that astar ibtc fees are set too low, so this pr also increases them.
> fix: enable astar tests and fix astar ibtc fee

- package.json
- scripts/chopsticks-test.ts
- src/adapters/polkadot.ts
- src/adapters/statemint.ts
- src/bridge.spec.ts
> Feat: Add routes between polkadot/kusama and their asset hubs

- package.json
- src/api-provider.ts
In order to avoid unexpected validation errors when trying to submit an extrinisic with the `assetId` option.
> Fix: avoid using acala wrapped api defs

- package.json
- src/adapters/statemint.ts
The previous XCM destination fee estimate  of 0.015 USDT for sending USDT from Kusama AssetHub to Kintsugi was too low.
Increasing the estimate to 0.02 USDT to keep it over 2x of the actual fees observed in chopsticks tests.
> Chore: update kusama asset hub fee estimate

- .github/workflows/xcm-tests.yml
- scripts/configs/acala.yml
- scripts/configs/astar.yml
- scripts/configs/bifrost-polkadot.yml
- scripts/configs/bifrost.yml
- scripts/configs/hydradx.yml
- scripts/configs/interlay.yml
- scripts/configs/karura.yml
- scripts/configs/kintsugi.yml
- scripts/configs/kusama.yml
- scripts/configs/parallel-heiko.yml
- scripts/configs/parallel.yml
- scripts/configs/polkadot.yml
- scripts/configs/statemine.yml
- scripts/configs/statemint.yml
Use upstream chopsticks with local config files (instead of a forked repo with custom docker contrainer) to run chopstick tests.
> Testing: Use acala-network chopsticks in tests

- scripts/configs/polkadot.yml
- src/adapters/statemint.ts
Some pallets started breaking test setup in chopsticks. Removed those from the config.
Additional changes:
- Bumped destination fee estimate for USDT from asset hub to interlay so the estimate is more than 2x the actual test fees.
> Test: fix polkadot config for chopsticks tests

- .gitignore
- scripts/configs/hydradx.yml
… to use their own wss endpoint rather than dwellir's.
Hopefully their endpoint reduces the test flakiness we've been observing.
> Chore: Switch HydraDX chopsticks test config

- .github/workflows/xcm-tests.yml
- scripts/chopsticks-test.ts
- scripts/configs/kusama.yml
- scripts/configs/polkadot.yml
- scripts/interlay-chopsticks-test.ts
Resolves #138
Changes:
- Reenable HydraDX chopsticks tests
- Modify ED check for HydraDX only to bump minimal amount's fees by 10%
The second part is to avoid issues where fees required change due to previous test transactions since HydraDX uses the token/HDX pair for fees which can slip and lead to false negatives.
This bump by an arbitrary percentage (10%) isn't perfect, but would at least catch some cases where the ED changes by a value that's in excess of actual fees plus 10%.
Given our fee estimate is 10x and tests start failing when the estimate is less than 2x the actual fee, the minimum amount returned by the XCM bridge should still be large enough to cover small changes in ED not caught.
> Test: Reenable HydraDX chopsticks tests

- .github/workflows/xcm-tests.yml
- package.json
- scripts/interlay-chopsticks-test.ts
- src/adapters/astar.ts
- src/adapters/hydradx.ts
- src/types.ts
Resolves #117 
- change Astar adapter to use `xTokens.transferMultiasset` extrinsic for sending
- enable chopsticks tests
- bump XCM bridge version number
> Chore: update Astar adapter

- .github/workflows/xcm-assethub-tests.yml
- .github/workflows/xcm-tests.yml
- package.json
- scripts/chopsticks-test.ts
- scripts/configs/parallel.yml
- scripts/interlay-chopsticks-test.ts
- scripts/kusama-chopsticks-assethub-test.ts
- scripts/polkadot-chopsticks-assethub-test.ts
Several fixes to try and make XCM chopsticks tests more stable and avoid some critical errors (particularly for AssetHub adapters) from hiding other issues.
Changes: 
- Separate tests involving AssetHub from other XCM tests
And run those on a slightly different schedule as the pre-existing XCM tests to avoid rate limiting due to opening too many channels at once.
- Reduce frequency of automated tests to every 2 hours (was: every hour)
This may alleviate some cases of rate limiting. In any event, given the significant amount of failures due to flakiness, we need to check in quite frequently anyway. So we do not gain much by running these tests every hour as opposed to every other hour.
- Disable ParallelFi adapter for chopsticks tests
Something seems to have changed on their end while I …
> Test: Make chopsticks tests more resilient

- package.json
- src/adapters/hydradx.ts
- src/adapters/interlay.ts
- Set destination weight to unlimited for hydradx to interlay transfers
- Increase destination fee estimate for USDT from kintsugi to asset hub
> Fix: Destination weights and fee estimates

- package.json
- src/adapters/polkadot.ts
Destination fees for DOT transfers to AssetHub have increased dramatically. Increase the fee estimate accordingly to have a safety buffer that is greater than the actual fees observed.
> Chore: increase assethub dest fee estimate

- package.json
- scripts/configs/hydradx.yml
- scripts/configs/interlay.yml
- scripts/configs/statemint.yml
- src/adapters/hydradx.ts
- src/adapters/interlay.ts
- src/adapters/statemint.ts
Resolves #165 
Add USDC as foreign asset and add route:
- Interlay <-> AssetHub
~~_Note_: PR #174 enables one additional USDC routes and is preferable over this PR, but only if chopsticks tests pass.~~
> Feat: Add USDC and initial routes

- package.json
- src/adapters/polkadot.ts
Resolves interlay/interbtc-ui#1644
Our previous hard-coded Polkadot extrinsic submission fee (for XCM transfers) turns out to be too low.
This PR bumps the estimate so transferring the max amount as indicated by the XCM lib prevents the Polkadot account being reaped.
0.06 DOT was just enough in local tests with chopsticks, but to be on the safe side, we're rounding that up to 0.1 DOT.
> Fix: Increase Polkadot extrinsic fee estimate

- .github/workflows/xcm-assethub-tests.yml
- .github/workflows/xcm-tests.yml
- scripts/interlay-chopsticks-test.ts
- scripts/kintsugi-chopsticks-test.ts
- bump chopsticks used in tests from `0.9.3` to `0.9.10`
- disable Acala and Karura tests
- XCM still seems to work (eg. stull seeing transfers succeed on subscan), therefore assumed false negative tests
- seems recent changes broke our tests, to be fixed in a later PR
> Tests: Bump chopsticks disable Acala, Karura

- README.md
- package.json
- scripts/configs/bifrost-polkadot.yml
- scripts/configs/interlay.yml
- src/adapters/bifrost.ts
- src/adapters/interlay.ts
This PR adds an XCM route for BNC between Bifrost and Interlay
:white_check_mark: Prerequisite: The [referendum to fix the asset registry location for BNC](https://interlay.subsquare.io/democracy/referenda/100) must pass and execute first.
> Feat: Add routes for BNC

- README.md
- scripts/configs/interlay.yml
- src/adapters/hydradx.ts
- src/adapters/interlay.ts
Adds XCM routes for HDX between HydraDX and Interlay.
Note: This is stacked on the PR adding BNC: #190
> Feat: Add HDX routes

- .github/workflows/xcm-assethub-tests.yml
- .github/workflows/xcm-tests.yml
- scripts/polkadot-chopsticks-assethub-test.ts
- Bump chopsticks version from `0.9.10` to `0.10.1` to fix test errors.
- Disable broken test case when sending USDC or USDT from Interlay to AssetHub
- AssetHub handling changed to converting those assets to DOT directly which seems to have broken our assertions. To be fixed as part of #194
> Test: Update chopsticks version

- .github/workflows/xcm-assethub-tests.yml
- .github/workflows/xcm-tests.yml
- package.json
- yarn.lock
Fix observed errors when trying to send XCM from Polkadot Asset Hub (or Polkadot relay chain) to another destination.
Updates:
- bump `polkadot/api` and `polkadot/types` to `11.0.2`
- and  bump acala dependencies to those using polkadot 11.0.2
- bump chopsticks version to `0.12.2` to be work with latest asset hub and relaychain versions
- increase XCM lib version to `0.6.0`
> Fix XCM relay and asset hub

- .github/workflows/xcm-tests.yml
- package.json
- scripts/chopsticks-test.ts
- scripts/configs/interlay.yml
- scripts/configs/phala.yml
- scripts/configs/statemine.yml
- scripts/configs/statemint.yml
- scripts/interlay-chopsticks-test.ts
- scripts/kintsugi-chopsticks-test.ts
- src/adapters/interlay.ts
- src/adapters/phala.ts
- src/bridge.spec.ts
- src/configs/chains/polkadot-chains.ts
TODO:
Notes / additional changes:
- deactivated Parallel Heiko tests; their only wss endpoint is unresponsive for extended periods of time
- implemented lower than usual fee overestimation factor config, and checks in tests for PHA as xcm costs are very high
> Feat: add Phala adapter for INTR and iBTC
